import Box, { BoxTypeMap } from '@mui/material/Box';

import Head from 'next/head'
import Header from '../components/header';
import Login from '../components/login';
import Map from '../components/map';
import type { NextPage } from 'next';
import isPropValid from '@emotion/is-prop-valid';
import { styled } from '@mui/system';
import useAuth from '../context/auth';
import { useState } from 'react';

const StyledBox = styled(Box, {
  shouldForwardProp: (prop) => isPropValid(prop.toString()) && prop !== 'target',
})(({ theme, color }) => ({
  background: theme.palette.home.background,
  color: theme.palette.home.color,
  height: 'fit-content',
  minHeight: '100vh',
  width: '100%',
  '& > div': {
    color: color,
  },
}));


const Home: NextPage = () => {
  const [key, setKey] = useState<string>('');
  const [isTracking, setIsTracking] = useState<boolean>(true);
  const {user, subscription} = useAuth();

  return (
    <StyledBox color="red">
      <Head>
        <title>The Next Rental</title>
        <meta name="description" content="Generated by The Next Rental" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Fall in love with your next home</h1>
      <br />
      <pre>
        {user === null ? <Login setIsTracking={setIsTracking} /> : JSON.stringify(user, null, 2)}
      </pre>
      <br />
      <pre>{JSON.stringify(subscription, null, 2)}</pre>
      <div className="helloWorld">Hello world in red</div>
      <Map />
    </StyledBox>
  );
}

export default Home;